config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  # get 'home/bio' => 'home#bio'
  # get 'home/bio', to: 'home#bio'

  get '/bio', to: 'home#bio', as: 'whatever_bio'


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def bio
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/bio.html.haml
.background2.container
  .row
    .backgroundContent
      %h2 Kurt Weber BIO

      %br
      %br

      .kurtCloseUp

      %h2 Work
      %p I work for a startup called Zipnosis which provides an online healthcare platform for healthcare organizations to compete in the telemedicine industry.  I joined Zipnosis as an intern in 2014. I was able to rejoin them one year after the spring of 2014 on a full time basis and i've been happy to stay with them ever since.

      %br
      %br

      %h2 Musician and Composer
      %p I have been a musician for a few years as well. I specialize in the piano and my greatet passion within the piano is composing my own original work. My first book was released in 2017, which was called Pebbles.  I also have all of my work on Spotify and other web streaming outlets. I continue to work on new material as I have time, however I don't think i'll ever make it a full time career as I have other hobbies and interests.

      .pianoImage

      %br
      %br

      %h2 Passions
      %p I am very dedicated to my church and have been involved within a fundraising effort to build a new church building near the University of Minnesota in Minneapolis.  The project is very near and dear to me and I am very excited to see it unfold and become a reality.

      %br
      %br

      .sailingImage

      %br
      %br

      %p An avid hockey fan, I spend my free time sailing or snowboarding depending on the seasons that Minnesota has to offer. I currently reside in Minneapolis MN.

app/views/home/index.html.haml
.background
  .layer
.container
  .row
    .frame
      %h2 Kurt Weber
      %p
      .break
        %ul{:style => "list-style-type:none"}
          %li Piano Composer.
          %li Web Developer.
          %li Entrepreneur.
          %li Tech Enthusiast.
          %li Life Long Learner.
      .col-md-3
        .fa.fa-twitter
        %p email me at: kdweber89@gmail.com
      .col-sm-2.text-center
        %h3
          =link_to "Bio", whatever_bio_path
      / .col-sm-2.text-center
      /   %h3 blog
      / .col-sm-2.text-center
      /   %h3 Pebbles

  .row
    .col-sm-1.fa.fa-twitter.fa-2x
    .col-sm-1.fa.fa-facebook.fa-2x

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title kdweber89
  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

  %link(href="https://fonts.googleapis.com/css?family=Arsenal" rel="stylesheet" type="text/css")


%body

= render 'shared/header'
= yield
/ = render 'shared/footer'

app/views/shared/_footer.html.haml
%h3 kdweber89 L.L.C

app/views/shared/_header.html.haml
/ %h3 This is my awesome header, in which I'm not quite sure what I'll do with it, but I find it possibly a little bit important.